### ISSUE TITLE
Placeholders don't get parsed

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#101]
Line 1 throws an error:

``` scss
%center-background-image {
  background-size: cover;
  background-position: center center;
}
```

Moved from #96.

/cc @cgtm
