### ISSUE TITLE
No selector before/after combinator throws error

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#102]
Line 1 throws error:

``` scss
nav.breadcrumb +  {
  padding-top: $margin-desktop-large;
}
```

Line 4 throws error:

``` scss
li {
  position: relative;
  margin-bottom: 0.5em;
  > i, > img {
    position: absolute;
    text-align: center;
  }
}
```

Please note, that having no selector before or after combinator is not valid in CSS, but is totally fine in scss and less.

Moved from #96.

/cc @cgtm
