### ISSUE TITLE
Interpolation in id throws error

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#103]
Line 1 throws error:

``` scss
// Sass
##{$nani} {
  color: tomato;
}
```

``` less
// Less
#@{nani}  {
  color: tomato;
}
```

Moved from #96.

/cc @cgtm
