### ISSUE TITLE
Single-line comments throw errors

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#104]
A very annoying one.
All single-line comments throw errors:

``` scss
$color-url: tomato;
// Comment 1
a {
  // Comment 2
  color: tomato;
}
```

Moved from #96.

/cc @jantimon
