### ISSUE TITLE
Parsing error when using extrapolated variable as extend name

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#110]
Getting a parse error with `%#{$var}` in the example below. From my testing it's caused by the `%` prefix for a silent placeholder.

SCSS, both current and dev-beta.

``` scss
$var: "foo";

%#{$var} {
  font-size: 18px;
}

.bar {
  @extend %foo;
}
```
