### ISSUE TITLE
Issue with css keyframes with percentage selectors

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#113]
Currently there is a parse error when you use a percentage selector within a keyframe animation.

This is with 3.0.3.

``` css
@keyframes anim {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```

While the following is ok

``` css
@keyframes anim {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
```
