### ISSUE TITLE
parse error with interpolation

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#115]
Hi @tonyganch 

Ive been running through all the reported issues on sass-lint with regards to parse errors, here's one that is still throwing a parse error in gonzales-pe 3.2.1

``` scss
left: calc(50% - #{$eb-hint-width / 2});
```

This parses fine however

``` scss
left: calc(50% - #{$eb-hint-width});
```

First reported [here](https://github.com/sasstools/sass-lint/issues/321)

**Comment by DanPurdy** [comment]
This is also still causing parse errors on every line you find `-#{$i}` in 3.2.1

``` scss
@for $i from 1 through length($brand-neutral-colors) {

  .background-color-index-neutral-#{$i},
  .background-color-index-neutral-#{$i + length($brand-neutral-colors)} {
    background-color: nth($brand-neutral-colors, $i);
  }

  .background-color-index-neutral-#{$i}-a,
  .background-color-index-neutral-#{$i + length($brand-neutral-colors)}-a {
    background-color: rgba(nth($brand-neutral-colors, $i), 0.8);
  }
}
```

Originally reported [here](https://github.com/sasstools/sass-lint/issues/222)
