### ISSUE TITLE
[CSS/LESS/SCSS] Should raise an error for missing semicolons

### ISSUE THREAD

**Issue by haoqunjiang** [tonyganch/gonzales-pe#145]
From this issue: https://github.com/csscomb/csscomb.js/issues/447

The following css block should not pass the parser:

``` css
.test {
    position: absolute
    display: block
    padding: 0 10px 0 0
    margin: auto
    color: red
    border-color: green
}
```
