### ISSUE TITLE
SCSS, Sass - Setting & as variable value causes parse issue

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#150]
Setting ampersand to be the value of a variable causes a parse error.

Both the following cause an issue.

``` scss
$parent: #{&};
$parent: &;
```

Original issue posted in sass-lint - https://github.com/sasstools/sass-lint/issues/385
