### ISSUE TITLE
Modulo parse error in .scss format

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#166]
The following is throwing a parse error due to the modulo operator being present.

``` scss
@for $i from 1 through length($listColors) {
    #{$i*(100/length($listColors))}% {
      fill: nth($listColors, $i);
    }
  }
```

When placed in the following context the whole of the above block is throwing a parse error even if the modulo operator is removed.

``` scss
@keyframes pweek {
  0% {
    fill: $firstColor;
  }
  @for $i from 1 through length($listColors) {
    #{$i*(100/length($listColors))}% {
      fill: nth($listColors, $i);
    }
  }
}
```
