### ISSUE TITLE
CSS, Sass, SCSS - [attr|=value] pipe causes parser error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#174]
The `|` in the following attribute selector causes Gonzales to parser error out :fire:

``` css
[attr|=value] {
  content: 'foo';
}
```
