### ISSUE TITLE
nth selector reversion in 3.3.5

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#194]
the following causes a parse error in 3.3.5

``` scss
&:nth-child(n+10) {
    visibility: hidden;
  }
```

the following work correctly

``` scss
&:nth-child(n+b) {
    visibility: hidden;
  }
```

``` scss
&:nth-child(1n+10) {
    visibility: hidden;
  }
```

Possibly related to https://github.com/tonyganch/gonzales-pe/pull/178
