### ISSUE TITLE
[CSS] Support custom properties (css variables)

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#197]
https://www.w3.org/TR/css-variables/

**Comment by tonyganch** [comment]
From [Sass 3.5 announcement](http://blog.sass-lang.com/posts/809572-sass-35-release-candidate):

So we decided on a compromise: we'd treat custom properties like we do selectors and at-rule values, and only allow #{} as a means of including Sass values. While technically this is plain CSS, it's a very small surface area and it's very easy to escape, so we're not too worried. This means that in 3.5 you can write:

``` css
 :host {
  --my-toolbar-theme: {
    background-color: #{$toolbar-background};
    border-radius: 4px;
    border: 1px solid gray;
  };
}
```
