### ISSUE TITLE
Using :global pseudo class with keyframes produces Fatal error

### ISSUE THREAD

**Issue by ukupat** [tonyganch/gonzales-pe#203]
We started using CSS Modules but we wanted to use some keyframes globally that were defined in .scss. For that we had to use `:global` pseudo class that takes an argument https://github.com/css-modules/css-modules#exceptions. Something like this:

``` css
@keyframes :global(alert--fadeout-animation) {
    0% { opacity: 1; }
    100% { opacity: 0; }
}
```

This is the only way to use keyframes globally because of https://github.com/css-modules/css-modules/issues/115

**Using :global with keyframes made sass-lint produce Fatal error results**:

``` javascript
2:1  error  Please check validity of the block starting from line #2  Fatal
```
