### ISSUE TITLE
parse error in font-face mixin with format syntax and multiple src

### ISSUE THREAD

**Issue by michaelwarren1106** [tonyganch/gonzales-pe#210]
for this SCSS

``` css
$base-font-family: 'ProximaNova' !default;
@mixin font-face($font-family, $file-name, $baseurl, $weight: 500, $style: normal ){
  @font-face {
    font: {
      family: $font-family;
      weight: $weight;
      style: $style;
    }
    src: url( $baseurl + $file-name + '.eot');
    src: url( $baseurl + $file-name + '.eot?#iefix') format('embedded-opentype');
    src: url( $baseurl + $file-name + '.woff') format('woff'),
           url( $baseurl + $file-name + '.woff2') format('woff2'),
           url( $baseurl + $file-name + '.ttf') format('truetype'),
           url( $baseurl + $file-name + '.svg' + '#' + $file-name) format('svg');
  }
}
```

I'm getting this error

``` shell
  18:1  error  Please check validity of the block starting from line #18  Fatal

✖ 1 problem (1 error, 0 warnings)
```

I've narrowed it down to the `format()` part. If i remove that, everything works, but that is valid css/scss, and I've not seen any other folks having problems with font-face syntax in general.

Little help?
