### ISSUE TITLE
Multiple interps without prefix in selector cause parse error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#212]
The following code with cause a parse error.

``` scss
$foo: '.foo';
$bar: 'bar;

#{$foo}-#{$bar} {
  content: 'baz';
}
```

Dynamic ID's also causes an issue;

``` scss
$foo: 'foo';
$bar: 'bar;

##{$foo}-#{$bar} {
  content: 'baz';
}
```

While classes are ok;

``` scss
$foo: 'foo';
$bar: 'bar;

.#{$foo}-#{$bar} {
  content: 'baz';
}
```
