### ISSUE TITLE
[SCSS|Sass] Parse error when interp directly follow attribute selectors

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#227]
Parse error caused by interps following attribute selectors. Fails in both SCSS and Sass.

```scss
select[multiple]#{$parent} {
  content: 'foo';
}
```
