### ISSUE TITLE
[Sass|SCSS] Extra comma with selectors causes parse error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#238]
The code below is valid in Sass, but not CSS. No surprises, this will give a parser error 😑 

```scss
div,, , span, ,, {
  color: red;
}
```

https://github.com/sass/sass-spec/blob/master/spec/basic/36_extra_commas_in_selectors/input.scss
