### ISSUE TITLE
[Sass|SCSS] Using double quotes within interp causes parse error

### ISSUE THREAD

**Issue by bgriffith** [tonyganch/gonzales-pe#239]
Using double quotes with an interp within an attribute selector causes a parse error.

The following code causes an error:
```scss
[attr="foo #{"bar"}"] { p:v }
```
While the following code is ok:
```scss
.foo {
 content: "foo #{"bar"}";
}
```
