### ISSUE TITLE
[sass] Doesn't support `>>>` combinator (shadow-piercing descendant combinator)

### ISSUE THREAD

**Issue by mattmischuk** [tonyganch/gonzales-pe#253]
A fatal error is returned if `>>>` selector is used (shadow-piercing descendant combinator).

https://drafts.csswg.org/css-scoping/#deep-combinator

Example:
```scss
:host >>> .test { color: red; }
```
