### ISSUE TITLE
Please add support for CSS mixins using @apply rule

### ISSUE THREAD

**Issue by JosefJezek** [tonyganch/gonzales-pe#260]
- https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins
- http://tabatkins.github.io/specs/css-apply-rule/

``` css
.Tooltip {
  --paper-tooltip: {
    font-size: 16px;
  };
}
```

```
Please check the validity of the block starting from line #2

1 | .Tooltip {
2*|         --paper-tooltip: {
3 |           font-size: 16px;
4 |         }

Gonzales PE version: 3.0.0-28
Syntax: css
```

https://github.com/csscomb/csscomb.js/issues/480
