### ISSUE TITLE
Background image infinite loop

### ISSUE THREAD

**Issue by DanPurdy** [tonyganch/gonzales-pe#282]
```scss
.test {
  background-image: url();
}
```

```sass
.test
  background-image: url()
```

Both of these are causing infinite loops it looks like.
