### ISSUE TITLE
Variable interpolation in SCSS not supported

### ISSUE THREAD

**Issue by kty** [tonyganch/gonzales-pe#56]
Variable interpolation in SCSS doesn't seem to be supported. 

Example code:

``` scss
$classes: .dog, .cat;

#{$classes},
.horse {
    color: red;
}
```

Results in "Parsing error: Please check the validity of the block starting from line #XXX".
