### ISSUE TITLE
LESS: using interpolated variables as selector names

### ISSUE THREAD

**Issue by ferrarit** [tonyganch/gonzales-pe#75]
The following valid less code, throws a parse error

``` less
@selector: a;
@{selector}{
    color: red;
}
```
