### ISSUE TITLE
LESS: ease-out function throws parsing error

### ISSUE THREAD

**Issue by immist** [tonyganch/gonzales-pe#77]
Given the following valid LESS code

``` less
@ease-out-function: cubic-bezier(0.23, 1, 0.32, 1);
.ease-out(@duration: 450ms; @property: all; @delay: 0ms) {
    .lh-transition(@property @duration @ease-out-function @delay);
}
```

Gonzales PE throws the following cryptic parsing error

```
Parsing error: Please check validity of the block



Syntax: undefined
Gonzales PE version: 3.0.0-29
```
