### ISSUE TITLE
[SCSS] 3.0.0-beta issues

### ISSUE THREAD

**Issue by cgtm** [tonyganch/gonzales-pe#96]
Hi,

I have the following code that is throwing the parser with "Warning: Parsing error at FILENAME: Please check validity of the block starting from line …"

Here's the beginning of the file, and the line that is mentioned in the error message is marked with ***:

``` scss
.layout-1 {
  @include breakpoint($breakpoint-large) {
    .section-header {
***      &.img { ***
        .content {
          @include span(first 15 of 24);
          // ensure text doesn't come too close to the image
          @if supports-browser('ie7') {
            .ie7 & {
              @include span(first 14 of 24); // Less the post 1
            }
          }
          @include post(1);
          // leave a 3 column gap
        }

      }
    }
  }
}
```

If I remove the ampersand before .img, it gets further but dies on the next line with an ampersand ( .ie7 &). Any idea what's going on here? The files all compile fine via ruby-based sass.

**Comment by tonyganch** [comment]
I'll take a look, thank you for report.

**Comment by cgtm** [comment]
Just added another bit to the end of my comment above. Thanks!!

**Comment by tonyganch** [comment]
In case you're interested, the problem is with parsing of selectors.
This line in particular: https://github.com/tonyganch/gonzales-pe/blob/dev/src/scss/parse.js#L3764
While checking if a substring is a type selector, I assume it may be an asterisk, an ident (just a word) or an interpolation.
What there should be is one more check for parent selector.
I guess I've somehow managed to have no tests with parent selectors :octopus:

**Comment by cgtm** [comment]
I'm converting quite a sizeable scss project from ruby sass to libsass via sass-lint. Is it helpful for me to continue to report problems of this nature?

**Comment by tonyganch** [comment]
Yes!

**Comment by cgtm** [comment]
Looks like percent sign throws it off too:

``` scss
%center-background-image {
  background-size: cover;
  background-position: center center;
}
```

**Comment by cgtm** [comment]
The plus sign is throwing it here:

``` scss
  section {
    padding: $margin-desktop-small 0 $margin-desktop-small;
    // Push the section down to allow space for the breadcrumb
    nav.breadcrumb +  {
      padding-top: $margin-desktop-large;
    }
  }
```

**Comment by cgtm** [comment]
An id of an interpolated value throws it:

``` scss
##{$non-js-selector} , .no-svg  {
  background-image: url(/assets/website/img/logo/site-logo.png);
}
```

**Comment by jantimon** [comment]
Just ran in the same issues when porting a codebase - here is one which hasn't been mentioned before:

```
$image-url: '../images/';
//
```

**Comment by benthemonkey** [comment]
And another (issue is at line 4):

```
div {
    $i: 1;

    @if $i % 2 == 1 {
        color: blue;
    } @else {
        color: red;
    }
}
```

**Comment by cgtm** [comment]
Last one from me! The immediate descendent selector (>) is throwing the parser off in here:

``` scss
li {
  position: relative;
  margin-bottom: 0.5em;
  > i, > img {
    position: absolute;
    text-align: center;
  }
}
```

**Comment by cgtm** [comment]
Weird. The issues reported by jantimon (https://github.com/tonyganch/gonzales-pe/issues/96#issuecomment-145567168) and benthemonkey (https://github.com/tonyganch/gonzales-pe/issues/96#issuecomment-145748834) don't cause any problems for me. Well, to the extent that I pasted their example code into my project and it didn't throw the parser.

**Comment by jantimon** [comment]
Maybe we could create a pull request and add the erros from above to the unit tests - so the bugs are easier to reproduce and to fix:
https://github.com/tonyganch/gonzales-pe/tree/master/test/scss

**Comment by tonyganch** [comment]
> Maybe we could create a pull request and add the erros from above to the unit tests - so the bugs are easier to reproduce and to fix

That would be awesome!
Just make sure that `dev` is the target branch, please:
https://github.com/tonyganch/gonzales-pe/tree/dev/test/scss

**Comment by cgtm** [comment]
@jantimon I've not worked with pull requests before, but am happy to contribute test code once it's in place.

**Comment by shellscape** [comment]
tossing my hat in here too, this is causing false-positive errors on our end as well.

**Comment by bgriffith** [comment]
Just to add that I'm also getting issues with `&`. Parse error on the line starting with `&:after`.

``` scss
.foo {
  &:after {
    content: 'foo';
  }
}
```

**Comment by bgriffith** [comment]
Another issue I have is that the `default` node type (`!default`) 's content is returning empty.

``` scss
$foo: red !default;
```

**Comment by bgriffith** [comment]
Also a parse issue with the `background` line below when there's a `no-repeat` at the end.

``` scss
.foo {
  $imagesUrl: '/images/';
  background: center url($imagesUrl + 'file.png') no-repeat;
}
```

When there isn't, there's no parse error.

``` scss
.foo {
  $imagesUrl: '/images/';
  background: center url($imagesUrl + 'file.png');
}
```
